In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
raw_data = pd.read_csv("data/merged_data_mass.csv")

data = raw_data[['A site charge', 'A site mass', 'B1 charge', 'B1 mass', 
                 'B2 charge', 'B2 mass','X site charge', 'X site mass', 'Elpasolite?']].copy()
B_data = raw_data[['A site charge', 'A site mass', 'B1 charge', 'B1 mass', 
                 'X site charge', 'X site mass', 'Elpasolite?']].copy()
print(data.columns)

Index(['A site charge', 'A site mass', 'B1 charge', 'B1 mass', 'B2 charge',
       'B2 mass', 'X site charge', 'X site mass', 'Elpasolite?'],
      dtype='object')


In [21]:
def random_forest(dataset, test_size, class_estimators, criterion):
    X = dataset.iloc[:, :-1].values
    y = dataset.iloc[:, -1].values
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 0)
    
    sc = StandardScaler()
    X_train, X_test = sc.fit_transform(X_train), sc.transform(X_test)
    
    
    
    classify = RandomForestClassifier(n_estimators = class_estimators, criterion = criterion, random_state = 0)
    classify.fit(X_train, y_train)
    
    y_pred = classify.predict(X_test)
    
    
    cm = confusion_matrix(y_test, y_pred)
    return(cm, classify.score(X_test, y_pred))
    

In [22]:
print(random_forest(data, .6495, 10, 'gini'))
print(random_forest(data, .6494, 10, 'entropy'))

(array([[41,  0],
       [ 0, 23]], dtype=int64), 1.0)
(array([[41,  0],
       [ 0, 22]], dtype=int64), 1.0)


In [23]:
print(random_forest(B_data, .6495, 10, 'gini'))
print(random_forest(B_data, .6494, 10, 'entropy'))

(array([[41,  0],
       [ 5, 18]], dtype=int64), 1.0)
(array([[41,  0],
       [ 0, 22]], dtype=int64), 1.0)
